apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-2048
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/currycan/argocd-vela.git
    targetRevision: master
    path: appfiles
    plugin:
      name: vela

  destination:
    server: https://kubernetes.default.svc
    namespace: docker-2048
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
